apiVersion: apps/v1beta1 
kind: Deployment 
metadata:
  name: georgemichael
spec:
  replicas: 2 
  template:
    metadata: 
      labels:
        app: georgemichael
    spec:
      containers:
       - image: "dinorows/georgemichael"
         imagePullPolicy: Always 
         name: georgemichael
         ports:
           - containerPort: 80
---
apiVersion: v1 
kind: Service 
metadata:
  name: georgemichael 
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: georgemichael
